[package]
name = "parquet-cat"
version = "0.1.0"
authors = ["James Hall <james.hall@shopify.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"
parquet = {git = "https://github.com/apache/arrow"}
